export const cuisines = [
    { id: 1, name: "all" },
    { id: 2, name: "burmese" },
    { id: 3, name: "chinese" },
    { id: 4, name: "european" },
    { id: 5, name: "french" },
    { id: 6, name: "hong kong" },
    { id: 7, name: "indonesian" },
    { id: 8, name: "italian" },
    { id: 9, name: "japanese" },
    { id: 10, name: "korean" },
    { id: 11, name: "malaysian" },
    { id: 12, name: "mexican" },
    { id: 13, name: "singaporean" },
    { id: 14, name: "spanish" },
    { id: 15, name: "thai" },
    { id: 16, name: "taiwanese" },
    { id: 17, name: "vietnamese" },
    { id: 18, name: "western" },
];
